#Database connection
spring:
  application:
    name: talia-web-management
  datasource:
    url: jdbc:mysql://localhost:3306/itcast
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 951897
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    bucketName: zaxiliu-java-ai
    region: cn-shanghai