server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: 黑马商城交易服务接口文档
    description: 黑马商城交易服务接口文档
    api-rule-resources: com.hmall.trade.controller
  db:
    database: hm-trade
    port: 3307